
fragment FragmentParagraphInterface on ParagraphInterface {
    __typename
    id
    behaviors
    status
}

fragment FragmentParagraphSulHomeImage on ParagraphSulHomeImage {
    ...FragmentParagraphInterface
    sulHomeImage {
        ...FragmentMediaImage
    }
    sulHomeImageCredits {
        ...FragmentText
    }
}

fragment FragmentParagraphSulHomeBanner on ParagraphSulHomeBanner {
    ...FragmentParagraphInterface
    sulHomeImages {
        ...FragmentParagraphSulHomeImage
    }
}

fragment FragmentParagraphSulLocationHour on ParagraphSulLocationHour {
    ...FragmentParagraphInterface
    sulLocHoursAlert {
        processed
    }
}

fragment FragmentParagraphCollection on ParagraphCollection {
    ...FragmentParagraphInterface
    sulCollectionCard {
        ...FragmentParagraphCollectionCard
    }
    sulCollectionHeading
}

fragment FragmentParagraphCollectionCard on ParagraphCollectionCard {
    ...FragmentParagraphInterface
    sulCard {
        ...FragmentParagraphStanfordCard
    }
    sulCardInfo
}

fragment FragmentParagraphSulButton on ParagraphSulButton {
    ...FragmentParagraphInterface
    sulButtonHeadline
    sulButtonLink {
        ...FragmentLink
    }
}

fragment FragmentParagraphSulContactCard on ParagraphSulContactCard {
    ...FragmentParagraphInterface
    sulContactAddress {
        ...FragmentAddressType
    }
    sulContactBranch {
        id
        path
    }
    sulContactEmail
    sulContactHours
    sulContactImage {
        ...FragmentMediaImage
    }
    sulContactLink {
        ...FragmentLink
    }
    sulContactMapLink {
        ...FragmentLink
    }
    sulContactPhone
    sulContactTitle
}

fragment FragmentParagraphSulFeatCollection on ParagraphSulFeatCollection {
    ...FragmentParagraphInterface
    sulCollectionCards {
        ...FragmentParagraphStanfordCard
    }
    sulCollectionHeadline
    sulCollectionLink {
        ...FragmentLink
    }
}

fragment FragmentParagraphSulLibguide on ParagraphSulLibguide {
    ...FragmentParagraphInterface
    sulLibguideDesc {
        processed
    }
    sulLibguideHeadline
    sulLibguideId
}

fragment FragmentParagraphStanfordAccordion on ParagraphStanfordAccordion {
    ...FragmentParagraphInterface
    suAccordionBody {
        ...FragmentText
    }
    suAccordionTitle
}

fragment FragmentParagraphStanfordBanner on ParagraphStanfordBanner {
    ...FragmentParagraphInterface
    suBannerHeader
    suBannerBody {
        ...FragmentText
    }
    suBannerSupHeader
    suBannerButton {
        url
        title
    }
    suBannerImage {
        ...FragmentMediaImage
    }
}

fragment FragmentParagraphStanfordCard on ParagraphStanfordCard {
    ...FragmentParagraphInterface
    suCardHeader
    suCardSuperHeader
    suCardBody {
        ...FragmentText
    }
    suCardLink {
        ...FragmentLink
    }
    suCardMedia {
        ...FragmentMediaUnion
    }
    sulCardImageCaption
    sulCardSuperHead {
        ... FragmentText
    }
}

fragment FragmentParagraphStanfordEntity on ParagraphStanfordEntity {
    ...FragmentParagraphInterface
    suEntityHeadline
    suEntityDescription {
        ...FragmentText
    }
    suEntityButton {
        url
        title
    }
    suEntityItem {
        ... on NodeInterface {
            id
            path
        }
    }
}

fragment FragmentParagraphStanfordGallery on ParagraphStanfordGallery {
    ...FragmentParagraphInterface
    suGalleryHeadline
    suGalleryDescription {
        ...FragmentText
    }
    suGalleryButton {
        url
        title
    }
    suGalleryImages {
        ...FragmentMediaStanfordGalleryImage
    }
}

fragment FragmentParagraphStanfordList on ParagraphStanfordList {
    ...FragmentParagraphInterface
    suListHeadline
    suListDescription {
        ...FragmentText
    }
    suListButton {
        url
        title
    }
    suListView {
        view
        display
        contextualFilter
        pageSize
    }
}

fragment FragmentParagraphStanfordMediaCaption on ParagraphStanfordMediaCaption {
    ...FragmentParagraphInterface
    suMediaCaptionMedia {
        ...FragmentMediaUnion
    }
    suMediaCaptionLink {
        url
        title
    }
    suMediaCaptionCaption {
        ...FragmentText
    }
}

fragment FragmentParagraphStanfordPersonCtum on ParagraphStanfordPersonCtum {
    ...FragmentParagraphInterface
    suPersonCtaName
    suPersonCtaTitle
    suPersonCtaLink {
        url
        title
    }
    suPersonCtaImage {
        ...FragmentMediaImage
    }
}

fragment FragmentParagraphStanfordSchedule on ParagraphStanfordSchedule {
    ...FragmentParagraphInterface
    suScheduleHeadline
    suScheduleDescription {
        ...FragmentText
    }
    suScheduleDateTime {
        ...FragmentSmartDateType
    }
    suScheduleLocation {
        ...FragmentAddressType
    }
    suScheduleUrl {
        url
        title
    }
    suScheduleSpeaker {
        ...FragmentParagraphStanfordPersonCtum
    }
}

fragment FragmentParagraphLayout on ParagraphLayout {
    ...FragmentParagraphInterface
}

fragment FragmentParagraphStanfordSpacer on ParagraphStanfordSpacer {
    ...FragmentParagraphInterface
    suSpacerSize
}

fragment FragmentParagraphStanfordWysiwyg on ParagraphStanfordWysiwyg {
    ...FragmentParagraphInterface
    suWysiwygText {
        ...FragmentText
    }
}

fragment FragmentParagraphStanfordPageTitleBanner on ParagraphStanfordPageTitleBanner {
    ...FragmentParagraphInterface
    suTitleBannerImage {
        ...FragmentMediaImage
    }
}

fragment FragmentParagraphStanfordFaq on ParagraphStanfordFaq {
    ...FragmentParagraphInterface
    created {
        ...FragmentDateTime
    }
    suFaqDescription {
        ...FragmentText
    }
    suFaqHeadline
    suFaqQuestions {
        ...FragmentParagraphStanfordAccordion
    }
}

fragment FragmentParagraphStanfordStatCard on ParagraphStanfordStatCard {
    ...FragmentParagraphInterface
    suStatBgColor {
        ... FragmentColorFieldType
    }
    suStatBody {
        ... FragmentText
    }
    suStatButton {
        ... FragmentLink
    }
    suStatCentered
    suStatHeadingHide
    suStatHeadline
    suStatHeadlineLvl
    suStatIcon {
        ... FragmentFontawesomeIconType
    }
    suStatIconColor {
        ... FragmentColorFieldType
    }
    suStatImage {
        ... FragmentMediaImage
    }
    suStatLinkStyle
    suStatStat
    suStatStatColor {
        ... FragmentColorFieldType
    }
    suStatSuperhead
}

fragment FragmentParagraphUnion on ParagraphUnion {
    ...FragmentParagraphInterface
    ...FragmentParagraphStanfordAccordion
    ...FragmentParagraphStanfordBanner
    ...FragmentParagraphStanfordCard
    ...FragmentParagraphStanfordEntity
    ...FragmentParagraphStanfordGallery
    ...FragmentParagraphStanfordList
    ...FragmentParagraphStanfordMediaCaption
    ...FragmentParagraphStanfordSpacer
    ... FragmentParagraphStanfordStatCard
    ...FragmentParagraphStanfordWysiwyg
    ...FragmentParagraphLayout
    ...FragmentParagraphCollection
    ...FragmentParagraphCollectionCard
    ...FragmentParagraphSulButton
    ...FragmentParagraphSulContactCard
    ...FragmentParagraphSulFeatCollection
    ...FragmentParagraphSulLibguide
    ...FragmentParagraphStanfordFaq
    ...FragmentParagraphSulHomeImage
    ...FragmentParagraphSulHomeBanner
    ...FragmentParagraphSulLocationHour
}
