# Each of the view queries.

fragment FragmentViewPageInfo on ViewPageInfo {
    page
    total
}


query sulStudyPlaces {
    sulStudyPlaces {
        results {
            ...FragmentNodeSulStudyPlaceTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query sulBranchLocations {
    sulBranchLocations {
        results {
            ...FragmentNodeSulLibraryTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query sulEvents($contextualFilters: SulEventsContextualFilterInput, $sortDir: SortDirection = ASC, $pageSize: Int, $page: Int = -1, $offset: Int) {
    sulEvents(contextualFilter: $contextualFilters, sortDir: $sortDir, sortKey: START_TIME, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordEventTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query sulEventsSharedTags($contextualFilters: SulEventsSharedTagsContextualFilterInput, $sortDir: SortDirection = ASC, $pageSize: Int, $page: Int = -1, $offset: Int) {
    sulEventsSharedTags(contextualFilter: $contextualFilters, sortDir: $sortDir, sortKey: START_TIME, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeStanfordEventTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}


query stanfordBasicPages($contextualFilters: StanfordBasicPagesContextualFilterInput, $sortKey: StanfordBasicPagesSortKeys, $sortDir: SortDirection $pageSize: Int = 3, $page: Int, $offset: Int) {
    stanfordBasicPages(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset, sortKey: $sortKey, sortDir: $sortDir) {
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordPageTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

#query stanfordCourses($contextualFilters: StanfordCoursesContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
#    stanfordCourses(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset) {
#        results {
#            ...FragmentNodeInterface
#            ...FragmentNodeStanfordCourse
#        }
#        pageInfo {
#            ...FragmentViewPageInfo
#        }
#    }
#}
#
#query stanfordEvents($contextualFilters: StanfordEventsContextualFilterInput, $pageSize: Int, $page: Int = -1, $offset: Int) {
#    stanfordEvents(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset, sortKey: START_TIME) {
#        results {
#            ...FragmentNodeInterface
#            ...FragmentNodeStanfordEventTeaser
#        }
#        pageInfo {
#            ...FragmentViewPageInfo
#        }
#    }
#}
#
#query stanfordEventsPastEvents($contextualFilters: StanfordEventsPastEventsContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
#    stanfordEventsPastEvents(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset, sortKey: START_TIME) {
#        results {
#            ...FragmentNodeInterface
#            ...FragmentNodeStanfordEventTeaser
#        }
#        pageInfo {
#            ...FragmentViewPageInfo
#        }
#    }
#}

query stanfordNews($contextualFilters: StanfordNewsContextualFilterInput, $filter: StanfordNewsFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
    stanfordNews(contextualFilter: $contextualFilters, filter: $filter, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordNewsTeaser
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordPerson($contextualFilters: StanfordPersonContextualFilterInput, $pageSize: Int, $page: Int = -1, $offset: Int) {
    stanfordPerson(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeInterface
            ...FragmentNodeStanfordPerson
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

#query stanfordPublications($contextualFilters: StanfordPublicationsContextualFilterInput, $pageSize: Int = -1, $page: Int, $offset: Int) {
#    stanfordPublications(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset) {
#        results {
#            ...FragmentNodeInterface
#            ...FragmentNodeStanfordPublicationTeaser
#        }
#        pageInfo {
#            ...FragmentViewPageInfo
#        }
#    }
#}

query stanfordSharedTags($contextualFilters: StanfordSharedTagsContextualFilterInput, $pageSize: Int = 3, $page: Int $offset: Int) {
    stanfordSharedTags(contextualFilter: $contextualFilters, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeInterface
            ...FragmentNodeTeaserUnion
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query search($filter: SearchFilterInput = {key: ""}, $pageSize: Int = 3, $page: Int $offset: Int) {
    search(filter: $filter, pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeInterface
            ...FragmentNodeUnion
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}

query stanfordPersonSearch($pageSize: Int = 999, $page: Int = 0, $offset: Int) {
    stanfordPerson(pageSize: $pageSize, page: $page, offset: $offset) {
        results {
            ...FragmentNodeInterface
            ... on NodeStanfordPerson {
                suPersonFirstName
                suPersonLastName
                suPersonFullTitle
                suPersonShortTitle
                suPersonPhoto {
                    ...FragmentMediaImage
                }
                body {
                    processed
                }
                suPersonEmail
                suPersonTelephone
                suPersonMailCode
                suPersonResearch {
                    processed
                }
                suPersonResearchInterests
            }
        }
        pageInfo {
            ...FragmentViewPageInfo
        }
    }
}
