mainConfiguration: https://github.com/SU-SWS/ace-sulgryphon
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true
