
name: Build & Lint
on: [push]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        NEXT_PUBLIC_DRUPAL_BASE_URL: ${{ secrets.NEXT_PUBLIC_DRUPAL_BASE_URL }}
        NEXT_IMAGE_DOMAIN: ${{ secrets.NEXT_IMAGE_DOMAIN }}
        BUILD_COMPLETE: ${{ secrets.BUILD_COMPLETE }}
    steps:
      - uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: 2.x-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            2.x-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
            2.x-${{ hashFiles('package.json') }}-
            2.x-
      - name: Lint
        run: |
          yarn
          yarn lint
      - name: Build
        run: |
          yarn build