
name: Build & Lint
on: [push]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    container:
      image: node:18.10
      env:
        NODE_ENV: development
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: |
          yarn
          yarn lint
