
name: Build & Lint
on: [push]
jobs:
  build-lint:
    runs-on: ubuntu-latest
    container:
      image: node:18
      env:
        BUILD_COMPLETE: ${{ secrets.BUILD_COMPLETE }}
        LIBGUIDE_CLIENT_ID: ${{ secrets.LIBGUIDE_CLIENT_ID }}
        LIBGUIDE_CLIENT_SECRET: ${{ secrets.LIBGUIDE_CLIENT_SECRET }}
        NEXT_PUBLIC_DRUPAL_BASE_URL: ${{ secrets.NEXT_PUBLIC_DRUPAL_BASE_URL }}
        NEXT_PUBLIC_SITE_NAME: ${{ secrets.NEXT_PUBLIC_SITE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: 2.x-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            2.x-${{ hashFiles('package.json') }}-${{ hashFiles('yarn.lock') }}
            2.x-${{ hashFiles('package.json') }}-
            2.x-
      - name: Lint
        run: |
          yarn
          yarn lint
      - name: Build
        run: |
          yarn build