
name: Update Dev & Test Branches
on:
  push:
    branches:
      - 'preview-auth'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-branches:
    runs-on: ubuntu-latest
    container:
      image: node:18.10
      env:
        NODE_ENV: development
        NEXT_PUBLIC_DRUPAL_BASE_URL: ${{ secrets.NEXT_PUBLIC_DRUPAL_BASE_URL }}
        NEXT_IMAGE_DOMAIN: ${{ secrets.NEXT_IMAGE_DOMAIN }}
    steps:
      - uses: actions/checkout@v3
        width:
          fetch-depth: 0
          ref: 1.x
      - name: Set git settings
        run: |
          git config --global user.email "sws-developers@lists.stanford.edu"
          git config --global user.name "Github Actions"
      - name: Update Dev Branch
        run: |
          git checkout 1.x
          git pull
          git checkout dev
          git pull
          git rebase 1.x
          git push
      - name: Update Test Branch
        run: |
          git checkout 1.x
          git pull
          git checkout test
          git pull
          git rebase 1.x
          git push
